version: "3.7"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=admin_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker_sql/01_set_up.sql:/docker-entrypoint-initdb.d/01_set_up.sql
